# Within this file, you can process the csi files generated by PicoScenes and
# output them into the format you want.
# Some parameters are provided below, please change them according to your needs.
# Copyright (c) 2023 Yilun Wang @The University of Sydney email:yilun.wang@sydney.edu.au
# Licensed under the MIT License

import matlab.engine
# Read the instruction for how to use Matlab in Python
from csi_add_time import csi_add_time
from polar_add_time import polar_add_time
from ML_data_generation_to_single_file import single_file
from ML_data_generation_to_multi_files import multi_files

# Your setting
csi_file_path = r'D:\Data_process\rx_1_230807_145641.csi'
csi_file_save_path = r'D:\Data_process\data1.h5'
Polar_file_path = r'D:\Data_process\Polar_H10_BF32822B_20230807_145635_RR.txt'
Polar_save_path = r'D:\Data_process\ground_truth.csv'
ML_data_path = r'D:\Data_process\data.h5'
ML_label_path = r'D:\Data_process\label.csv'
sampling_rate = 10
# Note that when modifying the sample rate, please also modify
# 'interval = timedelta(milliseconds=100).total_seconds()'
# located in the csi_add_time.py
# Files for data generation also need to be modified, please read the comments in the file
n_sub = 20
n_angle = 10
csi_record_end_time = '15:10:04.390194'
#%%
# start MATLAB
eng = matlab.engine.start_matlab()
eng.Farsenes_getdata_v2(csi_file_path,csi_file_save_path,sampling_rate,n_sub,n_angle,nargout = 0)
eng.quit()
#%%
# Adding timestamp to data
csi_add_time(csi_record_end_time, csi_file_save_path)
# Change Polar_file to csv
polar_add_time(Polar_file_path,Polar_save_path)
#%%
#Generating a single file of data for machine learning
single_file(Polar_save_path,csi_file_save_path,ML_data_path,ML_label_path)
#%%
#Generate multiple files of data for machine learning
#Please use the file to save the data
Multi_files_save_path = r'D:\Data_process\test'
label_name = 'label.csv'
multi_files(Polar_save_path,csi_file_save_path,Multi_files_save_path,label_name)